Fix 0.5.0 API breakage of decoder.decode(substrateFun=...)
pyasn1/pyasn1 pull request #39
Opened 2023-07-20 23:12 UTC by haxtibal

This fixes the API breakage regarding `decoder.decode(substrateFun=...)` in 0.5.0. See commit messages for details.

A `substrateFun` passed to `decoder.decode()` is now expected to be old-style, i.e.
- take 3 args instead of 4
- return (value, remainder)

A `substrateFun` passed to one of the new streaming decoders is expected to be new-style:
- take 4 args
- yield value
- remainder is what's left in the stream

I've considered [pysnmp 4.4.12 verdec.py](https://github.com/etingof/pysnmp/blob/master/pysnmp/proto/api/verdec.py#L15) and @ralphje s [example](https://github.com/pyasn1/pyasn1/issues/28#issuecomment-1518753039) as real world cases, both should work.

Fixes #28

2023-07-28 03:47 UTC, droideck requested changes
Awesome work! Thank you!
Could you also, please, add more comments to the code? (mostly, it'll be fine to copy your explanations from the commits, I think)

2023-07-28 03:47 UTC, droideck commented on pyasn1/codec/ber/decoder.py
> +                substrate.seek(-nbytes, os.SEEK_CUR)
I'm worrying a bit about the lack of error handling here. I think we need to check for different possible issues as it's done in [streaming.py](https://github.com/pyasn1/pyasn1/blob/main/pyasn1/codec/streaming.py)

2023-07-28 03:47 UTC, droideck commented on tests/codec/ber/test_decoder.py
> +            substrateFun=lambda a, b, c: (b, b[c:])
I think we should keep the old tests, too so we can confirm that both approaches work.

2023-07-28 03:51 UTC, droideck commented
@tiran please, when you have time, take a look at the PR too. You have more experience with the project so you may find more issues that I possibly missed.

Also, I'll try my luck and cast **_summon_** _@janpipek_, who has done a lot of awesome work on the streaming pyasn1 feature.
Jan, if you have time, could you please take a look at the issue too?

2023-07-29 22:13 UTC, haxtibal commented on pyasn1/codec/ber/decoder.py
> +                substrate.seek(-nbytes, os.SEEK_CUR)
`substrate` will always be of type `bytes` when entering `substrateFunWrapper`. That's an invariant ensured by `substrate = asSeekableStream(substrate)` and should be treated as that (I've added an assertion). Do you see further unhandled error cases?

2023-07-29 22:24 UTC, haxtibal commented on tests/codec/ber/test_decoder.py
> +            substrateFun=lambda a, b, c: (b, b[c:])
That's not only about tests, it also means there will be API variants to maintain. But it's doable. I've added it as two optional commits on top, so you can decide if you want to pick it or not.

2023-07-29 22:33 UTC, haxtibal commented
> Could you also, please, add more comments to the code?

Did that mostly in the form of docstrings, but have not yet checked if the resulting Sphinx docs make sense. Need to find some more time for it. Feel free to edit commits anyways.

2023-09-15 02:38 UTC, droideck requested changes
Sorry for the late review; I have so many things on my plate lately...

BTW, I also run the build with your changes here:
https://github.com/freeipa-pr-ci2/freeipa/pull/2968

Just to see how it behaves in a large IdM environment.

2023-09-15 02:38 UTC, droideck commented on pyasn1/codec/ber/decoder.py
> +                    assert isinstance(substrate, io.BytesIO)  # invariant maintained at Decoder.__call__ entry
Looks like the bandit CI for Python 3.10 fails here.

Can we just replace it with something like this?

```
if not isinstance(substrate, io.BytesIO):
    raise ValueError("substrate is not an instance of io.BytesIO")
```

If I understand correctly, it should fix the issue

2023-09-15 18:21 UTC, haxtibal commented
> Sorry for the late review; I have so many things on my plate lately...

No need to explain. I'm aware maintaining such projects is demanding and have great respect for those who do it - so thank you :-)

> BTW, I also run the build with your changes here: [freeipa-pr-ci2/freeipa#2968](https://github.com/freeipa-pr-ci2/freeipa/pull/2968)
> 
> Just to see how it behaves in a large IdM environment.

Nice idea. Will changed functions actually be triggered there? freeipa itself [doesn't seem to use pyasn1.codec.ber.decoder ](https://github.com/search?q=repo%3Afreeipa%2Ffreeipa+pyasn1.codec.ber&type=code) - only encoder.

2023-09-15 18:27 UTC, haxtibal commented on pyasn1/codec/ber/decoder.py
> +                    assert isinstance(substrate, io.BytesIO)  # invariant maintained at Decoder.__call__ entry
Ok, did that.

Not sure if I agree with [bandit B101: Test for use of assert](https://bandit.readthedocs.io/en/latest/plugins/b101_assert_used.html). We ensure an invariant by logic, the assert is mostly there to document it and shall be a no-op in production. Seems good to me - not so to bandit.

2023-09-15 19:05 UTC, droideck commented on pyasn1/codec/ber/decoder.py
> +                    assert isinstance(substrate, io.BytesIO)  # invariant maintained at Decoder.__call__ entry
Hmm, right. I've checked the bandit's doc and, I think, we can set the exclusion for this case: https://bandit.readthedocs.io/en/latest/config.html#exclusions

Something like? `# nosec B101`

2023-09-15 19:13 UTC, droideck commented
> > Sorry for the late review; I have so many things on my plate lately...
> 
> No need to explain. I'm aware maintaining such projects is demanding and have great respect for those who do it - so thank you :-)

Thank you for the kind words! And for your contributions!
 
> > BTW, I also run the build with your changes here: [freeipa-pr-ci2/freeipa#2968](https://github.com/freeipa-pr-ci2/freeipa/pull/2968)
> > Just to see how it behaves in a large IdM environment.
> 
> Nice idea. Will changed functions actually be triggered there? freeipa itself [doesn't seem to use pyasn1.codec.ber.decoder ](https://github.com/search?q=repo%3Afreeipa%2Ffreeipa+pyasn1.codec.ber&type=code) - only encoder.

Yep, still FreeIPA includes more projects as dependencies - so it's possible that it may affect one of them at some point of execution.

I also plan to run pysnmp and python-ldap with this PR (different versions, used in Fedora, at least).

And after that, I think, we are good. :)

P.S. I also see that `docs/readthedocs.org:pyasn1` is failing but I still haven't chance to look at that.

2023-09-17 16:33 UTC, haxtibal commented on pyasn1/codec/ber/decoder.py
> +                    assert isinstance(substrate, io.BytesIO)  # invariant maintained at Decoder.__call__ entry
> Something like? # nosec B101

Yes, that should be fine, done.

2023-09-17 16:38 UTC, haxtibal commented
> P.S. I also see that `docs/readthedocs.org:pyasn1` is failing but I still haven't chance to look at that.

Where can I watch it failing? `tox -e docs` works locally for me.

2023-10-03 23:54 UTC, droideck reviewed
Here are a couple more thoughts I got while rechecking the code before merging.

2023-10-03 23:54 UTC, droideck commented on pyasn1/codec/ber/decoder.py
> +                except TypeError:
I feel a bit uneasy seeing this `try-except TypeError` here as, I think, other TypeErrors can happen here which will invalidate the next part of the code flow too.

So I wonder if we can use something like  `num_params = len(inspect.signature(origSubstrateFun).parameters)` here (using `import inspect`).
What do you think?

2023-10-03 23:54 UTC, droideck commented on pyasn1/codec/ber/decoder.py
> +                    if not substrateFun:
Maybe I missed something. Could you please clarify - if `substrateFun` is used assuming there's a strict check for the length, wouldn't we end up in a possible security vulnerability? 

Wouldn't it be more correct to check if the caller actually wanted the partial decoding? (with some flag or something) And it was not requested explicitly, - reject with an error.

2023-10-07 06:43 UTC, haxtibal commented on pyasn1/codec/ber/decoder.py
> +                except TypeError:
> other TypeErrors can happen here which will invalidate the next part of the code flow too

Yes, it could invalidate code flow if someone else tried to explicitly handle that user exception. I don't think pyasn1 does it right now, but there could be external code.

However, `inspect.signature` comes with a performance penalty, which IMO matters because for networking applications `decoder.decode` tends to be in somewhat hot paths. We could consider using `inspect.isgeneratorfunction` instead. Here's the output of a simple timeit test using python 3.10:
```
Test                         repeats  time
Try-ok                       1000000  0.06018121799979781ms
Try-except                   1000000  0.3202192690000629ms
inspect.signature            1000000  5.682969701999809ms 
inspect.isgeneratorfunction  1000000  0.3277805679999801ms
```

If we want minimal performance impact also for the try-ok case, we could consider sticking with `try: ... except:`, but remember the exception and reraise it in case the second call also fails.

It'll take some time until I commit updates, am a bit short of time upcoming week.

2023-11-01 22:02 UTC, droideck commented on pyasn1/codec/ber/decoder.py
> +                except TypeError:
Right, `isgeneratorfunction` will be a better choice here, for sure.

P.S. I finished testing this PR, and I think we can merge it soon (next week?).

So if you can clarify these two of my comments (about `isgeneratorfunction` and the partial decoding comment below), we can proceed right away.
Sorry for the delay with this reply. And thank you once again for your time and contribution!

2023-11-02 17:56 UTC, haxtibal commented on pyasn1/codec/ber/decoder.py
> +                except TypeError:
I dropped the idea of `isgeneratorfunction` again, as the substrateFun is not strictly required
to be a generator function but merely must return something iterable. Instead, I've just proposed a modified try-except approach in 27ee979. I've thought about it rather carefully, and it's covered by test... but a second pair of eyes would be good. What do you think?

2023-11-02 18:42 UTC, haxtibal commented on pyasn1/codec/ber/decoder.py
> +                    if not substrateFun:
> if substrateFun is used assuming there's a strict check for the length

There was no such length check in <= 0.4.8. The check was first drafted in b2aaaad638e5f5be825b9fff7d0ce333d2e51abd, then squashed into 7bdade5 during PR etingof/pyasn1#176. It's hard for me to reason about it.

@janpipek, if you're reading, could you explain the reason for adding `if bytesRead != length: raise PyAsn1Error()` back then?

> wouldn't we end up in a possible security vulnerability?

I don't see immediately how it could be exploited, but that's of course the weakest possible assessment.

> Wouldn't it be more correct to check if the caller actually wanted the partial decoding? (with some flag or something)

But old substrateFuns out there don't set such a flag. If we expect it now, wouldn't we reintroduce 0.4.8 incompatibility?

2023-11-04 17:20 UTC, janpipek commented on pyasn1/codec/ber/decoder.py
> +                    if not substrateFun:
I guess (sorry, it's been a few years and I am completely out of the project now, having forgotten everything) this was a double check that an explicitly stated byte length should be held and if not, then something was amiss (the stream, the bytes in it...). Not sure how important such check is if the "substrateFun"s can actually be even more creative and dangerous in their behaviour.

2023-11-07 20:52 UTC, droideck requested changes

2023-11-07 20:52 UTC, droideck commented on pyasn1/codec/ber/decoder.py
> +            substrateFunV4: Callable[[base.Asn1Type, bytes, int], tuple[object, bytes]],
Older Python versions' CI started to fail here...
```TypeError: 'type' object is not subscriptable```

2023-11-07 21:03 UTC, droideck commented on pyasn1/codec/ber/decoder.py
> +                    if not substrateFun:
Thank you, Jan!

Okay, I think we can leave it as it is in this PR and add a comment in the documentation about the situation and possible but unlikely issues (so when somebody has a special substrateFun function, they need to take additional care here).

We can implement a partial decoding parameter flag for the future version that will take care of that. Hopefully, we'll be able to keep the 0.4.8 compatibility, as I think we can set it to some default value.

@haxtibal @janpipek  What do you think? Sounds good?

2023-11-07 22:28 UTC, haxtibal commented on pyasn1/codec/ber/decoder.py
> +            substrateFunV4: Callable[[base.Asn1Type, bytes, int], tuple[object, bytes]],
Yes, type hints require Python >= 3.5. Removed them. Supporting 2.7 is quite a burden...

2023-11-07 23:14 UTC, haxtibal commented on pyasn1/codec/ber/decoder.py
> +                    if not substrateFun:
> What do you think? Sounds good?

How about 08fdf9c4f140552bd55f50625ad083bdd21c701d?

> We can implement a partial decoding parameter flag

Not sure if such an `allowPartialDecoding=True` flag is required. This classifies it as something dangerous, but is it really dangerous?

2023-11-08 19:32 UTC, droideck commented on pyasn1/codec/ber/decoder.py
> +                    if not substrateFun:
I like it!
I think it's a good middle ground, and as you mentioned in the commit message, we can come back to it if it breaks someone else's case.

I think, though, that it'll be better to leave one part as it is. So to have a strict case for non-custom substrateFun and "loose" case for custom substrateFun.
Something like this?

```python
bytesRead = substrate.tell() - original_position
# custom substrateFun may be used for partial decoding, reading less is expected there
if (substrateFun and bytesRead > length) or (not substrateFun and bytesRead != length):
    error_msg = "more than" if substrateFun else "instead of"
    raise PyAsn1Error(f"Read {bytesRead} bytes {error_msg} the expected {length} bytes.")
```

2023-11-09 22:42 UTC, haxtibal commented on pyasn1/codec/ber/decoder.py
> +                    if not substrateFun:
Changed and squashed into earlier length check commit, to clean up history.

2023-11-09 22:49 UTC, haxtibal commented
@droideck The commit series was structured for optional cherry picking. If you're going to take the whole set, please tell me, then I'd squash some of them for nicer history.

2023-11-10 01:34 UTC, droideck commented
> @droideck The commit series was structured for optional cherry picking. If you're going to take the whole set, please tell me, then I'd squash some of them for nicer history.

Yes, please, squash them the way you like (I'll be okay even with one combined commit).
Besides that, I'm

2023-11-10 13:54 UTC, haxtibal commented
> Besides that, I think we are good! I'll run a bunch of tests one more time over the weekend and I'll do the build next week first thing! Yay!
> 
> Thank you for all of the work you've done! It's very structured and nicely executed. :)

Let's see... Will keep watching to help in case of regressions.

2023-11-14 22:38 UTC, droideck approved these changes
The results are good (there are some failures but they seems to be not related to this change - https://github.com/freeipa-pr-ci2/freeipa/pull/3139)
And I ran pysnmp, python-ldap and 389-ds-base tests with the new scratch-build.
All good!

Let's merge it then if you are okay with that. :)

2023-11-14 23:28 UTC, haxtibal commented
> there are some failures, but they seem to be not related to this change - [freeipa-pr-ci2/freeipa#3139](https://github.com/freeipa-pr-ci2/freeipa/pull/3139)

Tried to look into runner.log and report.html and couldn't find immediate hints about root causes. But it's a large test system. I can't really reason about it. This is up to you...

> Let's go ahead and merge it then if you are okay with that. :)

If you're confident then I'm too - let's go.
 
> Thank you for all of the great work! This contribution is VERY appreciated!

Thank *you* :)

2023-11-15 00:41 UTC, merged